### `SQL_Queries/BigQuery_DDL_Staging.sql`

```sql
-- UPPER-CASE DESCRIPTION: BIGQUERY_TABLE_DEFINITIONS_FOR_ADVERSE_ACTIONS
-- Project ID: driiiportfolio

CREATE OR REPLACE TABLE `driiiportfolio.tfb_underwriting.raw_adverse_actions`
(
    RECORD_ID STRING NOT NULL,
    POLICY_NUMBER STRING,
    NOTIFICATION_DATE DATE,
    ACTION_TYPE STRING,
    POLICY_TYPE STRING,
    REASON_SOURCE STRING,
    INDICATOR_60D INT64,
    ZIP_CODE STRING,
    EFFECTIVE_DATE DATE,
    REASON_CODES STRING,
    THIRD_PARTY_IND STRING,
    AERIAL_IMAGERY INT64
);

-- CREATE A DATA QUALITY METADATA TABLE TO TRACK EXCEPTIONS
CREATE OR REPLACE TABLE `driiiportfolio.tfb_underwriting.dq_exception_log`
(
    EXCEPTION_ID STRING DEFAULT GENERATE_UUID(),
    RECORD_ID STRING,
    CHECK_NAME STRING,
    SEVERITY STRING, -- HIGH (Blocking), MEDIUM (Warning)
    ERROR_DESCRIPTION STRING,
    LOG_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);
```
